name: f1-win

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - ipykernel
  - jupyterlab
  - requests
  - pyarrow
  - seaborn
  - streamlit
  - pip
  - pip:
    - plotly==5.18.0
    - tenacity>=8.0.0
    - packaging>=21.0

