name: f1-win
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - streamlit==1.31.0
    - pandas==2.1.4
    - numpy==1.26.3
    - scikit-learn==1.4.0
    - plotly==5.18.0
    - pyarrow==14.0.2
    - tenacity>=8.0.0
    - packaging>=21.0

